services:
  mysql-core:
    image: mysql:8.0
    container_name: mysql-core
    env_file:
      - ../../.env
    ports:
      - "3307:3306" # Access on ur own lap via 3307
    command: --innodb_buffer_pool_size=1G 
    deploy:
      resources:
        limits:
          memory: 1.5G
    networks:
      - capstone-net
    volumes:
      - mysql_data:/var/lib/mysql

networks:
  capstone-net:
    external: true